version: '3.8'
services:
  web:
    build: .
    container_name: coffee-app-api
    environment:
      POSTGRES_HOST: db
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffeeapp
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: