"""empty message

Revision ID: 0611ed62238d
Revises: 675210a40f58
Create Date: 2024-07-12 19:59:23.557543

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0611ed62238d"
down_revision: Union[str, None] = "675210a40f58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
